[window]
startup_mode = "Maximized"
#opacity = 0.90
#decorations = "none"

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
key = "LBracket"
mods = "Command"
chars = "\\p"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command"
chars = "\\n"

[shell]
program = "wsl --cd /home/lmiller"
